language: minimal
#python: '3.10'

#sudo: required

services:
  - docker

before_install:
  - docker build -t ayodeji32/frontend ./FrontEnd/
  - docker build -t ayodeji32/backend ./backend/

  
after_success:
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ayodeji32/frontend
  - docker push ayodeji32/backend

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: segmentation-app5
  env: Segmentationapp5-env
  bucket_name: elasticbeanstalk-us-east-1-944509782810
  bucket_path: segmentation-app5
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY