language: python

sudo: required

branches:
  ony:
    - master

services:
  - docker

before_install:
  - docker build -t ayodeji32/segmentation_app:frontend ./FrontEnd/
  - docker build -t ayodeji32/segmentation_app:backend ./backend/
  
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ayodeji32/segmentation_app:frontend
  - docker push ayodeji32/segmentation_app:backend

  # end-to-end-ml-pipelines-1