sudo: required

services:
  - docker

before_install:
  - docker build -t ayodeji32/customer_segmentation .  #End-to-End-ML-Pipelines-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ayodeji32/customer_segmentation