language: python

sudo: required

branches:
  ony:
    - master

services:
  - docker

before_install:
  - docker build -t ayodeji32/end-to-end-ml-pipelines-1:segmentation-frontend ./FrontEnd/
  - docker build -t ayodeji32/end-to-end-ml-pipelines-1:segmentation-backend ./backend/
  
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ayodeji32/end-to-end-ml-pipelines-1:segmentation-frontend
  - docker push ayodeji32/end-to-end-ml-pipelines-1:segmentation-backend