version: "3"
services:
  backend:
    container_name: backend
    build: ./backend/
    #command: "heroku container:push backend" # "python fastapp.py"
    ports:
      - "8000:8000"
    networks: #user defined network bridge for all containers
      - jcnet

  frontend:
    container_name: frontend
    build: ./FrontEnd/
    #command: "heroku container:push frontend" #"python -m streamlit run Single_Predict.py --server.port 8080"
    ports:
      - "80:80"
    networks:
      - jcnet
networks:
  jcnet: