version: 2.1 # CircleCI version
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/End-to-End-ML-Pipelines-1
    steps:
        - checkout
        - run: |
              docker-compose up -d 
              sudo curl https://cli-assets.heroku.com/install.sh | sh
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push frontend
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release frontend
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push backend
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release backend
workflow:
  build_and_push:
    jobs:
      - build